call plug#begin()

" List your plugins here
Plug 'pseewald/vim-anyfold'
" Plug 'neoclide/coc.nvim', { 'branch': 'release' }
Plug 'chriszarate/yazi.vim'
" Plug 'EdenEast/nightfox.nvim'

call plug#end()



set nocompatible
set filetype=on
" set syntax=off
set cursorline
set relativenumber
set autoindent
set smartindent
set expandtab
set smarttab
set shiftwidth=4
set tabstop=4
set nowrap
set hlsearch
set scrolloff=5
set splitright

set background=dark
colorscheme quiet
" colorscheme carbonfox

noremap zz za
noremap z. zz
nnoremap <silent> - :Yazi<cr>
nnoremap <silent> _ :YaziWorkingDirectory<cr>

autocmd FileType text,markdown,tex setlocal spell



" recommended vim-anyfold config

filetype plugin indent on " required
syntax on                 " required

autocmd Filetype * AnyFoldActivate               " activate for all filetypes
" or
autocmd Filetype <your-filetype> AnyFoldActivate " activate for a specific filetype

set foldlevel=0  " close all folds
" or
set foldlevel=99 " Open all folds
